USING `unm`;

-- 학생 데이터 테이블 구성
CREATE TABLE IF NOT EXISTS `student` (
    id CHAR(16) UNIQUE PRIMARY KEY NOT NULL,
    grade TINYINT(3) UNSIGNED NOT NULL,
    classNo TINYINT(9) UNSIGNED NOT NULL,
    classNumber TINYINT UNSIGNED NOT NULL,
    name VARCHAR(6) NOT NULL
);

-- 학생 출석 스케줄 테이블 구성
CREATE TABLE IF NOT EXISTS `schedule` (
    id CHAR(8) UNIQUE PRIMARY KEY NOT NULL,
    classNo TINYINT(9) NOT NULL, posX TINYINT NOT NULL, posY TINYINT NOT NULL,
    monA1 BOOLEAN NOT NULL DEFAULT 0, monN1 BOOLEAN NOT NULL DEFAULT 0, monN2 BOOLEAN NOT NULL DEFAULT 0, 
    tueA1 BOOLEAN NOT NULL DEFAULT 0, tueN1 BOOLEAN NOT NULL DEFAULT 0, tueN2 BOOLEAN NOT NULL DEFAULT 0,
    thuA1 BOOLEAN NOT NULL DEFAULT 0, thuN1 BOOLEAN NOT NULL DEFAULT 0, thuN2 BOOLEAN NOT NULL DEFAULT 0,
    friA1 BOOLEAN NOT NULL DEFAULT 0, friN1 BOOLEAN NOT NULL DEFAULT 0, friN2 BOOLEAN NOT NULL DEFAULT 0,
    FOREIGN KEY(id) REFERENCES student(id)
);

-- 학생 출석 정보 테이블 구성
CREATE TABLE IF NOT EXISTS `attendanceInfo` (
    _id BIGINT AUTO_INCREMENT PRIMARY KEY,
    id CHAR(8) UNIQUE NOT NULL,
    attendanceTime TIMESTAMP NOT NULL,
    period CHAR(2) NOT NULL,
    FOREIGN KEY(id) REFERENCES student(id)
);

-- 학생증 발급 정보 테이블 구성
CREATE TABLE IF NOT EXISTS `user` (
    _id BIGINT AUTO_INCREMENT PRIMARY KEY,
    id CHAR(8) UNIQUE NOT NULL,
    username VARCHAR(32) UNIQUE NOT NULL,
    email VARCHAR(320) UNIQUE NOT NULL,
    password VARCHAR(97) NOT NULL,
    role TINYINT NOT NULL DEFAULT 0, -- 0: student, 1: admin, 2: checkout-device
    FOREIGN KEY(id) REFERENCES student(id)
);